version: "3"
services:
  mariadb:
    container_name: lnmp-mariadb
    build: {}
    image: mariadb:10.7.8
    networks:
      - default-network
    volumes:
      - default_mariadb_data:/var/lib/mysql
    depends_on: []
    ports: []
    environment:
      - MARIADB_ROOT_PASSWORD=123456
  nginx:
    container_name: lnmp-nginx
    build: {}
    image: nginx:stable-alpine
    networks:
      - default-network
    volumes:
      - D:\repo\github.com\lixiang4u\docker-lnmp\dockerfile\nginx\log:/var/log/nginx
      - D:\repo\github.com\lixiang4u\docker-lnmp\dockerfile\nginx\config:/etc/nginx/conf.d
      - D:\repo\github.com\lixiang4u\docker-lnmp\dockerfile\nginx\html:/apps/www/default.me:ro,bind
      - D:\repo\github.com\lixiang4u\docker-lnmp\dockerfile\nginx\html:/apps/www/api.local.me:ro,bind
      - D:\repo\github.com\lixiang4u\docker-lnmp\dockerfile\nginx\html:/apps/www/m.local.me:ro,bind
      - D:\repo\github.com\lixiang4u\docker-lnmp\dockerfile\nginx\html:/apps/www/d.local.me:ro,bind
      - D:\repo\github.com\lixiang4u\docker-lnmp\dockerfile\nginx\html:/apps/www/tv.local.me:ro,bind
    depends_on:
      - php
      - mariadb
      - redis
    ports:
      - 80:80
      - 443:443
    environment: []
  php:
    container_name: lnmp-php72
    build:
      dockerfile: dockerfile/script/lamp-php-fpm
    image: ""
    networks:
      - default-network
    volumes:
      - D:\repo\github.com\lixiang4u\docker-lnmp\dockerfile\nginx\html:/apps/www/api.local.me:ro,bind
      - D:\repo\github.com\lixiang4u\docker-lnmp\dockerfile\nginx\html:/apps/www/m.local.me:ro,bind
      - D:\repo\github.com\lixiang4u\docker-lnmp\dockerfile\nginx\html:/apps/www/d.local.me:ro,bind
      - D:\repo\github.com\lixiang4u\docker-lnmp\dockerfile\nginx\html:/apps/www/tv.local.me:ro,bind
    depends_on: []
    ports: []
    environment: []
  phpmyadmin:
    container_name: lnmp-sql-admin
    build: {}
    image: phpmyadmin:latest
    networks:
      - default-network
    volumes: []
    depends_on: []
    ports: []
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=lnmp-mariadb
      - PMA_PORT=3306
      - UPLOAD_LIMIT=512M
  redis:
    container_name: lnmp-redis
    build: {}
    image: redis:latest
    networks:
      - default-network
    volumes:
      - default_redis_data:/data
    depends_on: []
    ports: []
    environment: []
networks:
  default-network: null
volumes:
  default_mariadb_data: null
  default_redis_data: null